### ISSUE TITLE
Violating Open source license.

### ISSUE THREAD

**Issue by rurimo** [linkinamine/vivy#7]
Hi, Mohamed El Amine BenAllouch.

I'm watching your GitHub profile for a few weeks, I apologize if you were offended
I noticed you are violating the open-source license by another famous developer.

It seems you applied some Germany companies without license or comments from the copied repository. If you really are a software developer, this behavior is against ethics.
I sent an email to the original author about this kind of violating.

And these codes are violated in your repository. (Apache-2.0 LICENSE)

https://github.com/linkinamine/vivy/blob/master/app/src/main/java/com/benallouch/vivy/api/ApiResponse.kt
=> https://github.com/skydoves/TheMovies2/blob/master/app/src/main/java/com/skydoves/themovies2/api/ApiResponse.kt

https://github.com/linkinamine/vivy/blob/master/app/src/main/java/com/benallouch/vivy/api/ResponseTransformer.kt
=> https://github.com/skydoves/TheMovies2/blob/master/app/src/main/java/com/skydoves/themovies2/api/ResponseTransformer.kt

https://github.com/linkinamine/vivy/blob/master/app/src/main/java/com/benallouch/vivy/compose/DispatchViewModel.kt
=> https://github.com/skydoves/TheMovies2/blob/master/app/src/main/java/com/skydoves/themovies2/compose/DispatchViewModel.kt

https://github.com/linkinamine/vivy/blob/master/app/src/main/java/com/benallouch/vivy/compose/ViewModelFragment.kt
=> https://github.com/skydoves/TheMovies2/blob/master/app/src/main/java/com/skydoves/themovies2/compose/ViewModelFragment.kt

**Comment by linkinamine** [comment]
@rurimo, thanks for the issue. 
I am new to open source development, do you have any recommendations ?

**Comment by linkinamine** [comment]
@rurimo, thanks for reporting the issue. 
I am new to open source development, I have pushed the changes with Apache2.0 licenses: https://github.com/linkinamine/vivy/commit/1a375bf69dd4b0fbfd9dd060392d98fa02405ef5

**Comment by linkinamine** [comment]
Fixed the issue, and talked to the original developer: 

> I think you already realized the issue and thanks for complying with the open-source license.
